import type { ManifestFields } from "../core/types.ts";

/**
 * The twenty competitors, fixed order. Every consumer -- season configs, the
 * bracket seeding, the site -- uses exactly this roster.
 *
 * The first six (aggressor through blitzen) are copied verbatim from the
 * manifests already registered in the database (see `competitor_versions`).
 * Their playstyle, strategies, features, historyPlies, fallback and budget
 * must not change: any change is a new version and breaks the cross-season
 * identity those names already carry.
 *
 * Measured fact from eleven live experiments (2026-09-18): the playstyle
 * prose is the only lever that measurably changes play. The strategy and
 * feature lists below are declared to match what each sentence claims, and
 * budgets scale with how much a persona is meant to deliberate.
 */
export const ROSTER: readonly ManifestFields[] = [
  {
    name: "aggressor",
    model: "jev-latest",
    playstyle:
      "Hunts the king from move one and accepts material risk to keep the initiative.",
    strategies: ["attack", "develop", "king-hunt"],
    features: ["materialBalance", "kingSafety", "opponentMateInOne", "lastMoveThreatValue"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "architect",
    model: "jev-latest",
    playstyle: "Builds slowly, trades only when the resulting structure is better.",
    strategies: ["develop", "fortify", "trade-down"],
    features: ["materialBalance", "mobility", "kingSafety", "development"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "mason",
    model: "jev-latest",
    playstyle: "Builds a structure first and only then looks for a target.",
    strategies: ["develop", "fortify", "direct"],
    features: ["materialBalance", "mobility", "development", "kingSafety"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "ledger",
    model: "jev-latest",
    playstyle: "Never loses material and grinds out endings.",
    strategies: ["trade-down", "simplify", "endgame"],
    features: ["materialBalance", "mobility", "hangingOwnPieces"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "economist",
    model: "jev-latest",
    playstyle: "Counts everything, spends nothing, and wins endings.",
    strategies: ["trade-down", "simplify", "endgame"],
    features: ["materialBalance", "mobility", "hangingOwnPieces", "phase"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "blitzen",
    model: "jev-latest",
    playstyle: "Attacks the king relentlessly and sacrifices for tempo.",
    strategies: ["attack", "king-hunt", "develop"],
    features: ["materialBalance", "kingSafety", "opponentMateInOne"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "gambit",
    model: "jev-latest",
    playstyle: "Gives up a pawn or more early to open lines and seize the initiative.",
    strategies: ["attack", "direct", "king-hunt"],
    features: ["materialBalance", "mobility", "opponentMateInOne", "lastMoveThreatValue"],
    historyPlies: 6,
    fallback: "greedy",
    budget: { maxMs: 9000 },
    hierarchical: true,
  },
  {
    name: "fortress",
    model: "jev-latest",
    playstyle:
      "Locks the position down and refuses every exchange that would crack its own structure.",
    strategies: ["fortify", "defend", "simplify"],
    features: ["kingSafety", "hangingOwnPieces", "mobility", "phase"],
    historyPlies: 10,
    fallback: "greedy",
    budget: { maxMs: 13000 },
    hierarchical: true,
  },
  {
    name: "vulture",
    model: "jev-latest",
    playstyle:
      "Makes the safest available move and waits for the opponent to hang material, then takes it.",
    strategies: ["defend", "direct", "simplify"],
    features: ["hangingOpponentPieces", "hangingOwnPieces", "materialBalance"],
    historyPlies: 4,
    fallback: "greedy",
    budget: { maxMs: 6000 },
    hierarchical: false,
  },
  {
    name: "metronome",
    model: "jev-latest",
    playstyle: "Plays the same developing plan every game, regardless of what the opponent does.",
    strategies: ["develop"],
    features: ["development", "phase"],
    historyPlies: 2,
    fallback: "first-legal",
    budget: { maxMs: 3000 },
    hierarchical: false,
  },
  {
    name: "swindler",
    model: "jev-latest",
    playstyle:
      "Steers toward complications and traps when its position is worse, hoping the opponent slips.",
    strategies: ["attack", "direct", "develop"],
    features: ["materialBalance", "opponentMateInOne", "inCheck", "lastMoveWasCapture"],
    historyPlies: 6,
    fallback: "random-legal",
    budget: { maxMs: 8500 },
    hierarchical: true,
  },
  {
    name: "hermit",
    model: "jev-latest",
    playstyle: "Avoids contact, trading pieces off and steering into quiet, closed positions.",
    strategies: ["simplify", "trade-down", "fortify"],
    features: ["mobility", "opponentMobility", "phase"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 10000 },
    hierarchical: false,
  },
  {
    name: "scholar",
    model: "jev-latest",
    playstyle: "Follows standard opening development and known plans before improvising.",
    strategies: ["develop", "direct"],
    features: ["development", "mobility", "materialBalance"],
    historyPlies: 10,
    fallback: "greedy",
    budget: { maxMs: 7000 },
    hierarchical: false,
  },
  {
    name: "surgeon",
    model: "jev-latest",
    playstyle: "Waits until it finds one decisive tactical strike, then commits everything to it.",
    strategies: ["direct", "attack"],
    features: ["materialBalance", "hangingOpponentPieces", "opponentMateInOne", "lastMoveThreatValue"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 15000 },
    hierarchical: true,
  },
  {
    name: "anvil",
    model: "jev-latest",
    playstyle:
      "Absorbs pressure without conceding structure, then counterattacks once the opponent overextends.",
    strategies: ["defend", "fortify", "attack"],
    features: ["hangingOwnPieces", "kingSafety", "lastMoveThreatValue", "materialBalance"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 12000 },
    hierarchical: true,
  },
  {
    name: "tinker",
    model: "jev-latest",
    playstyle: "Makes the smallest available improving move each turn rather than committing to a plan.",
    strategies: ["develop", "simplify", "fortify"],
    features: ["mobility", "development", "kingSafety"],
    historyPlies: 4,
    fallback: "greedy",
    budget: { maxMs: 5000 },
    hierarchical: false,
  },
  {
    name: "mirror",
    model: "jev-latest",
    playstyle: "Matches the opponent's last move in kind: aggression with aggression, caution with caution.",
    strategies: ["direct", "attack", "defend"],
    features: ["lastMoveWasCapture", "lastMoveAttacks", "lastMoveThreatValue", "materialBalance"],
    historyPlies: 6,
    fallback: "greedy",
    budget: { maxMs: 8000 },
    hierarchical: true,
  },
  {
    name: "compass",
    model: "jev-latest",
    playstyle: "Commits to one strategic direction early and steers every move toward it.",
    strategies: ["direct", "develop", "endgame"],
    features: ["materialBalance", "development", "phase"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 10000 },
    hierarchical: true,
  },
  {
    name: "hourglass",
    model: "jev-latest",
    playstyle:
      "Moves quickly through the opening to bank time, then spends most of its budget calculating the middlegame and endgame.",
    strategies: ["develop", "direct", "endgame"],
    features: ["phase", "materialBalance", "mobility"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 13000 },
    hierarchical: true,
  },
  {
    name: "sentry",
    model: "jev-latest",
    playstyle: "Defends its king above every other consideration, refusing plans that leave it exposed.",
    strategies: ["defend", "fortify"],
    features: ["kingSafety", "hangingOwnPieces", "inCheck"],
    historyPlies: 8,
    fallback: "greedy",
    budget: { maxMs: 9000 },
    hierarchical: false,
  },
] as const;
